package com.aerolinea.entidad;
// Generated 03-sep-2017 11:25:17 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

    @NotEmpty(message="El campo Usuario es obligatorio")
    @NotNull(message="El campo Usuario es obligatorio")
    private String idusuario;
    
    @NotEmpty(message="El campo Nombres es obligatorio")
    @NotNull(message="El campo Nombres es obligatorio")
    private String nombres;
    
    @NotEmpty(message="El campo Apellidos es obligatorio")
    @NotNull(message="El campo Apellidos es obligatorio")
    private String apellidos;
    
    @NotEmpty(message="El campo Email es obligatorio")
    @NotNull(message="El campo Email es obligatorio")
    private String email;
    
    private String telefono;
    
    @NotEmpty(message="El campo Clave es obligatorio")
    @NotNull(message="El campo Clave es obligatorio")
    private String clave;
    
    @NotEmpty(message="El campo Confirmar Clave es obligatorio")
    @NotNull(message="El campo Confirmar Clave es obligatorio")
    private String clave2;
    
    private Pais pais;
    
    private Rol rol;

    private Set<Reservacion> reservacions = new HashSet<Reservacion>(0);

    private boolean cambiarClave = false;
    
    public Usuario() {
        this.cambiarClave = true;
    }

    public Usuario(String idusuario, Pais pais, Rol rol, String nombres, String apellidos, String email, String clave) {
        this.idusuario = idusuario;
        this.pais = pais;
        this.rol = rol;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.email = email;
        this.clave = clave;
    }

    public Usuario(String idusuario, Pais pais, Rol rol, String nombres, String apellidos, String email, String telefono, String clave, Set<Reservacion> reservacions) {
        this.idusuario = idusuario;
        this.pais = pais;
        this.rol = rol;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.email = email;
        this.telefono = telefono;
        this.clave = clave;
        this.reservacions = reservacions;
    }

    @Id
    @Column(name = "idusuario", unique = true, nullable = false, length = 30)
    public String getIdusuario() {
        return this.idusuario;
    }

    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idpais", nullable = false)
    public Pais getPais() {
        return this.pais;
    }

    public void setPais(Pais pais) {
        this.pais = pais;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idrol", nullable = false)
    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    @Column(name = "nombres", nullable = false, length = 45)
    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    @Column(name = "apellidos", nullable = false, length = 45)
    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    @Column(name = "email", nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "telefono", length = 20)
    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    @Column(name = "clave", nullable = false, length = 100)
    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    @Transient
    public String getClave2() {
        return this.clave2;
    }

    public void setClave2(String clave2) {
        this.clave2 = clave2;
    }
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set<Reservacion> getReservacions() {
        return this.reservacions;
    }

    public void setReservacions(Set<Reservacion> reservacions) {
        this.reservacions = reservacions;
    }

    @Transient
    public boolean isCambiarClave() {
        return cambiarClave;
    }

    public void setCambiarClave(boolean cambiarClave) {
        this.cambiarClave = cambiarClave;
    }

   
}
